### ISSUE TITLE
RFE: provide readline-friendly escape definitions

### ISSUE THREAD

**Issue by brrzap** [dslackw/colored#5]
i ran across this issue trying to colorize a prompt with stylize().  when used with readline, color sequences need to be wrapped with `\x01` ... `\x02` codes to tell readline to exclude the escape characters from width calculations.  the symptom is weird linewrapping issues.

a `stylize_rl` function that operates like `stylize()` but adds wraps each nonprinting sequence in the  might be appropriate.  apparently some terminals can misinterpret these bytes if they're found in normal printing, so i don't recommend adding them to the main `stylize()`.

demonstration code follows -- the colored.stylize() example was generated with `colored.stylize("[@user]: ", fg('red'))`.

    import readline
    
    # problem examples.  output of various libraries
    P1='\x1b[38;5;1m[@user]: \x1b[0m'      # colored.stylize()
    P2='\x1b[31m[@user]: \x1b[0m'          # termcolor.colored()
    P3='\x1b[31m[@user]: \x1b(B\x1b[m'     # blessings.Terminal.foo

    # fix -- wrap nonprinting codes in \x01 ... \x02
    Pa='\x01\x1b[38;5;1m\x02[@user]: \x01\x1b[0m\x02'
    Pb='\x01\x1b[31m\x02[@user]: \x01\x1b[0m\x02'
    Pc='\x01\x1b[31m\x02[@user]: \x01\x1b(B\x1b[m\x02'

    while True:
        # just hold down your 'a' key here and watch it wrap.
        # problem = wraps too early, no linefeed, & overwrites prompt.
        stuff = input(P1)

see also:
http://bugs.python.org/issue20359
https://unix.stackexchange.com/a/105974/222377

**Comment by dslackw** [comment]
Thank you very much for report. Fixed and it is ready the next release.

**Comment by dslackw** [comment]
Ok, keep going to submit.

**Comment by brrzap** [comment]
closing as completed; thanks!
