### ISSUE TITLE
Is is not work

### ISSUE THREAD

**Issue by mihalt** [dslackw/colored#8]
Hello! Look my session 
![image](https://user-images.githubusercontent.com/30621622/34604577-0c01989a-f211-11e7-99e1-4f9cfd40e974.png)

I have installed python 3.6, Windows 7

**Comment by dslackw** [comment]
Sorry works only with GNU/Linux OS mentioned in the [requirements.txt](https://github.com/dslackw/colored/blob/master/requirements.txt) file.
