### ISSUE TITLE
Ability to decolorize

### ISSUE THREAD

**Issue by alexanderad** [dslackw/colored#9]
We have a case when the output of the entire script here and there is colored with `colored`, but at times we want to remove colors globally. Is there any API function, which would be able to remove all the color codes from a string?

**Comment by dslackw** [comment]
Hi @alexanderad,
Have you try ```attr('reset')``` ?

**Comment by alexanderad** [comment]
Hey @dslackw, thanks for the super fast reply!
Hmm... but doesn't it reset the style for the message in question only?

Generally I'm looking for something like 
```python
def strip_colors(message):
    # strip all the color codes
    return message

colored_message = colored.stylize(...)

print(strip_colors(colored_message))
```

But perhaps my scenario is too specific, and I should do it myself. Story is that I'm looking for some way to disable the colorization globally: I have a script, which has colored applied here and there (across multiple modules, unfortunately), with no single place. And it used only to print to stdout. I added file writing with a sort of hack:

```python
class LogToFileAndStdout(object):
    def write(self, message):
        sys.stdout.write(message)
        self.log_file.write(strip_colors(message))

sys.stdout = LogToFileAndStdout()
```
